server:
  port: 8082
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: commerce0634@gmail.com
    password: 3406Commerce
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  data:
    mongodb:
      uri: mongodb+srv://ecommerce:ecommerce@demoappcluster-kisgy.mongodb.net/test?retryWrites=true&w=majority
